// Auto-generated by generate-example-docs.mjs - do not edit
import React from 'react';
import ManimExample from '../ManimExample';

async function animate(scene: any) {
  const { StreamLines } = await import('manim-web');

  // Matches Python manim ContinuousMotion example exactly:
  // func = lambda pos: np.sin(pos[0] / 2) * UR + np.cos(pos[1] / 2) * LEFT
  // UR = [1, 1, 0], LEFT = [-1, 0, 0]
  const streamLines = new StreamLines({
    func: (x, y) => [Math.sin(x / 2) - Math.cos(y / 2), Math.sin(x / 2)],
    strokeWidth: 3,
    maxAnchorsPerLine: 30,
  });
  scene.add(streamLines);

  streamLines.startAnimation({
    warmUp: false,
    flowSpeed: 1.5,
  });

  await scene.wait(streamLines.virtualTime / 1.5);
}

export default function StreamLinesContinuousMotionExample() {
  return <ManimExample animationFn={animate} />;
}
