// Auto-generated by generate-example-docs.mjs - do not edit
import React from 'react';
import ManimExample from '../ManimExample';

async function animate(scene: any) {
  const { NumberPlane, StreamLines, BLACK } = await import('manim-web');

  const plane = new NumberPlane({
    xRange: [-7, 7, 1],
    yRange: [-4, 4, 1],
    backgroundLineStyle: {
      color: '#333355',
      strokeWidth: 0.5,
      opacity: 0.3,
    },
  });
  scene.add(plane);

  const streamLines = new StreamLines({
    func: (x, y) => [
      Math.sin(x / 2) + Math.cos(y / 2) * 0.5,
      Math.cos(x / 2) * 0.5 - Math.sin(y / 2),
    ],
    xRange: [-6, 6, 0.5],
    yRange: [-3.5, 3.5, 0.5],
    numLines: 25,
    strokeWidth: 3,
    maxLineLength: 12,
    stepSize: 0.08,
    opacity: 0.9,
  });
  scene.add(streamLines);

  streamLines.startAnimation({
    warmUp: true,
    flowSpeed: 1.5,
    timeWidth: 0.3,
  });

  await scene.wait(10);

  streamLines.endAnimation();
}

export default function StreamLinesContinuousMotionExample() {
  return <ManimExample animationFn={animate} />;
}
